baseurl = "https://www.anotherblog.org/"
languageCode = "en-us"
title = "Just another SDE blog"
theme = "cactus"
copyright = "Mehdi HAROUN" # cactus will use title if copyright is not set
disqusShortname = "mehdey" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-1234-5"


# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[menu.main]]
name = "Certifications"
url = "/certification"
weight = 5

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]

  colortheme = "dark" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default

  # Home page settings
  description = "Tech enthusiast blogging about .NET Coding, Azure Cloud and Agile"
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = true # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/mehdyHD" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "02-01-2006" # default

  # Post page settings
  show_updated = true # default
  showReadTime = true # default

  [params.comments]
    enabled = false # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/mehdyHD"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/harounmehdi/"
  [[params.social]]
    name = "email"
    link = "harounmehdi90@gmail.com"  # no need for "mailto:" in the head
